thegazelle-ad/gazelle-server

__tests__/expandCache-test.js, package.json, src/components/AppController.jsx, src/components/Article.jsx, src/components/ArticleController.jsx, src/components/ArticleList.jsx, src/components/ArticlePreview.jsx, src/components/Author.jsx, src/components/AuthorController.jsx, src/components/AuthorList.jsx, src/components/CategoryController.jsx, src/components/EditorsPicks.jsx, src/components/FeaturedArticle.jsx, src/components/Footer.jsx, src/components/IssueController.jsx, src/components/Navigation.jsx, src/components/NotFound.jsx, src/components/TextPage.jsx, src/components/TextPageController.jsx, src/components/Trending.jsx, src/components/editor/EditAuthorsForm.jsx, src/components/editor/EditorArticleController.jsx, src/lib/falcor/FalcorRouter.js, src/lib/ghostAPI.js, src/styles/components/_featured-article.scss, src/styles/components/_navigation.scss, static/editorStyles.css, webpack.config.js
Adds linting output to console when compiling with Webpack; Resolves issue #27
=> Webpack linting

package.json, src/components/AppController.jsx, src/components/Article.jsx, src/components/ArticleController.jsx, src/components/ArticleList.jsx, src/components/ArticlePreview.jsx, src/components/Author.jsx, src/components/AuthorController.jsx, src/components/AuthorList.jsx, src/components/CategoryController.jsx, src/components/EditorsPicks.jsx, src/components/FeaturedArticle.jsx, src/components/Footer.jsx, src/components/IssueController.jsx, src/components/Navigation.jsx, src/components/NotFound.jsx, src/components/TextPage.jsx, src/components/TextPageController.jsx, src/components/Trending.jsx, webpack.config.js
Added CSS `autoprefixer` as plugin for `postcss-loader`.
Minified CSS output for better performance.
Resolved issue #22 
_Note: `autoprefixer-loader` as a `css-loader` plugin is depricated._
=> Add CSS autoprefixer

package.json, src/client.js, src/components/AppController.jsx, src/components/ArticleController.jsx, src/components/AuthorController.jsx, src/components/CategoryController.jsx, src/components/IssueController.jsx, src/components/Loader.jsx, src/components/TextPageController.jsx, src/lib/falcor/FalcorController.js, src/lib/falcor/falcorUtils.js, src/lib/utilities.js, src/styles/base/_layout.scss, src/styles/components/_loader.scss, src/styles/main.scss, src/styles/pages/_issue.scss
Replaced 'Loading' text with top of page progress bar
=> Add progress bar

package.json, src/components/AppController.jsx, src/components/Article.jsx, src/components/ArticleController.jsx, src/components/ArticlePreview.jsx, src/components/IssueController.jsx, src/components/Navigation.jsx, src/components/SharingButtons.jsx, src/styles/abstracts/_variables.scss, src/styles/base/_layout.scss, src/styles/base/_typography.scss, src/styles/components/_article-preview.scss, src/styles/components/_article.scss, src/styles/components/_featured-article.scss, src/styles/components/_navigation.scss, src/styles/components/_sharing-buttons.scss, src/styles/components/_trending.scss, src/styles/main.scss
Added dynamic share buttons to article previews and articles
=> Add social media share buttons

src/components/Author.jsx, src/components/AuthorController.jsx, src/components/CategoryController.jsx, src/styles/abstracts/_mixins.scss, src/styles/components/_author-list.scss, src/styles/components/_author.scss, src/styles/components/_navigation.scss, src/styles/main.scss, src/styles/pages/_category.scss, static/sample-issue/posts.js
Made category and author article lists display as vertical lists
=> Vertical list

src/server.js
Added hash query params for css and client.js
Resolves #4
=> Added MD5 hash for static served files

src/components/Article.jsx, src/components/ArticleController.jsx, src/components/CategoryController.jsx, src/components/IssueController.jsx, src/components/Navigation.jsx, src/styles/abstracts/_mixins.scss, src/styles/abstracts/_variables.scss, src/styles/base/_base.scss, src/styles/base/_layout.scss, src/styles/components/_article-list.scss, src/styles/components/_article.scss, src/styles/components/_featured-article.scss, src/styles/components/_footer.scss, src/styles/components/_navigation.scss, src/styles/components/_trending.scss, src/styles/pages/_category.scss, src/styles/pages/_issue.scss
Added related articles section at the bottom of the Article component
=> Related articles

package.json, src/server.js
Added gzip compression to served files
Resolves #32
=> Added compression to serving

src/components/ArticleController.jsx, src/components/AuthorController.jsx, src/components/CategoryController.jsx, src/components/IssueController.jsx, src/components/NotFoundController.jsx, src/components/TextPageController.jsx, src/lib/routes.js, src/styles/components/_not-found.scss, src/styles/main.scss
Added 404 not found error handling
=> Not found page

src/components/AppController.jsx, src/components/ArticleController.jsx, src/components/AuthorController.jsx, src/components/Navigation.jsx
Adds conditional fetching of Navigation data to AppController to dynamically render the appropriate publication date, categories and issue number for the content shown.
Data from the current issue is shown unless the user is on an archived issue page or archived article page.
Resolves #66
=> Added dynamic navigation support

src/components/Archives.jsx, src/components/ArchivesController.jsx, src/components/Footer.jsx, src/lib/falcor/FalcorController.js, src/lib/loader.js, src/lib/routes.js, src/styles/components/_archives.scss, src/styles/main.scss
=> Added archives page

package.json, src/client.js
Added Google Analytics tracking with `react-ga` package
Resolved #62
=> Added react-ga

src/lib/db.js, src/lib/falcor/FalcorRouter.js
The connection between teams and authors is still missing, but you can begin code review. This already covers queries and manipulations to the teams table.
=> Added backend for team querying, creating and updating

src/components/IssueController.jsx, src/components/MailingListButton.jsx, src/styles/components/_mailing-list-button.scss, src/styles/main.scss
Added mailing list signup button to issues page
=> Mailing list

src/components/ArticleList.jsx, src/lib/falcor/FalcorRouter.js, src/server.js
- Hotfixed a bug from Ghost
- Added a catch to a promise that otherwise crashed the code on error
- Removed an erroneous isRequired (some authors have no articles, otherwise maybe we wanna pass an empty array or something, this could be fixed otherwise, open to suggestions)
- Removed silenced logs
=> Fix serverside render bugs

circle.yml, package.json, scripts/getGhostConfig.sh, scripts/helperFiles/getGhostConfig.js
This resolves #143. 
This PR:
- Updates a lot of scripts to correctly throw exit codes 
- configures CircleCI
- adds linting script to package.json
Won't be seen in code but I have also in combination with this:
- Updated PR settings so we now have to pass CircleCI status checks before being able to merge
=> Add CircleCI continuous integration

circle.yml, scripts/deployment/config.ssh, scripts/deployment/deploy-beta.sh, scripts/deployment/deploy-production.sh
This resolves #166.
This PR:
- Added small deployment scripts for CircleCI to call
- Changed CircleCI config to auto deploy
What you cannot see was also done:
- Emil's user ssh key was deleted on the Scaleway server as this was insecure and incorrect. Two read-only deploy keys have instead been added to the server, one for this repository and one for the database-and-ghost-blog-server repository so they can pull changes. All repo editing should happen outside the server.
- I may add a bit of code to the server deployment scripts that calls the Slack API so deployments can be tracked, I'll see what's the best way to do it after checking that this indeed works. Maybe I can put it in the repo but it may be inconvenient because of API keys.
- This PR on one hand fixes this issue but is also a …
=> Added auto deployment to CircleCI

http-error-static-pages/5xx-static-html-generator.py, http-error-static-pages/5xx.template.html, static/500.html
Add: version one of the error 500 page to github.
=> Add error 500 page

src/server.js
@zanemountcastle I'll just use my admin privileges to merge this in right away as it's an obvious fix, and I tested it works as well.
=> Fixed missed linting fix bug regarding beta redirect to /login

src/components/editor/EditorAppController.jsx, src/components/editor/EditorLogin.jsx, src/lib/utilities.js
This PR switches the custom hash value to SHA512 for somewhat better security because of fewer hash collisions.
This is a very rough hotfix and should be replaced by Google OAuth ASAP.
=> Editor Tools Security

__tests__/env-tests/beta.test.js, __tests__/env-tests/development.test.js, __tests__/env-tests/production.test.js, __tests__/expandCache.test.js, __tests__/pathSetsInCache.test.js, npm-shrinkwrap.json, package.json, src/components/editor/lib/__tests__/form-field-updaters.test.js, src/lib/__tests__/server-utilities.test.js, src/lib/__tests__/utilities.env-tests.js, src/lib/falcor/__tests__/expandCache.test.js, src/lib/falcor/__tests__/pathSetsInCache.test.js
Been wanting to do this for a while especially because it removes the annoying default of mocking all functions. And then I thought I'd just do it now quickly so that @zanemountcastle can use it in #193 instead of using old syntax.
=> Upgrade Jest to v20

src/components/Navigation.jsx
Just the update of the nav bar, simple stuff. I also already updated the database on the server.
=> Update nav bar categories

src/components/Login.jsx
As mentioned in title, this is a hotfix I noticed when trying to access the beta page.
=> Update beta login hash value for new hash function

.circleci/config.yml
As described above, this is also first step towards adding our first end to end tests into CircleCI :)
=> Add workflows and parallelism to our CircleCI config

scripts/helpers/upload-database-dump.js
I'm fast tracking this one as it's just a small fix and because I just realized our backups of the database have actually been failing silently recently <.<. So many structural things we want to do better in this project haha.
=> Fix file name of client secret for Google API

src/components/editor/EditorIssueArticleController.jsx, src/components/editor/EditorMainIssueController.jsx, src/lib/db.js
This was mainly to increase pre publish validation for #218 and to make life a little easier for the editors, but actually also found a bug in db.js because I had missed some falcor paths in there (as it was bad style of me ever putting them there) when I renamed all the falcor paths. So probably merge this one with a rebase merge when doing it as I already modularized my commits with their own purpose.
Also @zanemountcastle if you could review and merge this as soon as you wake up (or if you're awake now), then that would be great, then the editors can use it tomorrow for their publishing.
edit: resolves #218
=> Increase pre publish validation

package-lock.json, static/admin.css
resolves #270 Changing the font of the header in the admin page
=> Admin interface name styling

__tests__/end-to-end/admin-tests/notfound.test.js, src/components/admin/NotFound.jsx
=> Fix #245 add E2E test for admin not found

src/lib/db.js
I was just being an SQL newb earlier and now there are enough semesters in the db for it to actually show up the bugs. I'll merge this straight in as it's pretty simple and I don't think anyone can review sql anyway
=> Fix get latest semester

.circleci/config.yml
=> Reenable autodeploy to staging

src/components/main/InteractiveArticle.jsx
Should just be straight mergeable as it's super simple, will let CI pass first
=> use new Function instead of eval as it's supposedly faster

README.md
Changed the Readme and added a wiki as required for the project setup #307.
=> Initial commit.

src/lib/db.js, src/lib/falcor/routes/articles/by-slug.js, src/lib/falcor/routes/authors/by-slug.js, src/lib/falcor/routes/categories/by-index.js, src/lib/falcor/routes/categories/by-slug.js, src/lib/falcor/routes/info-pages.js, src/lib/falcor/routes/issues/by-number.js, src/lib/falcor/routes/issues/meta.js, src/lib/falcor/routes/search/authors.js, src/lib/falcor/routes/search/posts.js, src/lib/falcor/routes/search/teams.js, src/lib/falcor/routes/semesters/by-name.js, src/lib/falcor/routes/semesters/meta.js, src/lib/falcor/routes/teams/by-index.js, src/lib/falcor/routes/teams/by-slug.js, src/lib/falcor/routes/trending.js
Now that other people with experience will see my code I'm suddenly motivated to hide the most horrible parts from when I knew less about for example how to import everything from a file haha (would be even better to just import the functions we need as the original reason for importing everything was that the FalcorRouter was a single file, but now I split it into several, didn't want to spend the time on that right now though, as we pass through we can maybe do that)
=> Properly import and export db functions

.eslintrc, CODEOWNERS, knexfile.js, migrations/20180325204028_remove-unused-ghost-tables.js, migrations/20180325211342_migrate-posts.js, migrations/20180326110614_cleanup-tag-tables.js, package-lock.json, package.json, src/lib/db.js
resolves #315 and fixes #316 
Also snuck in a CODEOWNERS update here
=> Update database tables for Ghost Removal

src/lib/db.js, src/lib/falcor/falcor-utilities.js, src/lib/falcor/routes/articles/by-slug.js
This resolves #317 
It will be an absolutely horrible PR to review, so maybe just don't and we'll do thorough QA on this when I have all the jigsaw pieces so the code actually can run (still have to do #318). I still think it's nice to get this PR in separately though as then following PRs won't be bloated by this renaming. I'll also look through it a second time at the places where I know it was more critical / error-prone
=> [#317] Rename tables and columns for database refactor

docs/dev-environment/setting-up-dev-environment.md, package.json
Adding a post merge (which is the way to add a post pull) hook as I discussed with @frederikbrinck earlier that might be convenient
=> Add post merge hook

src/components/main/ArticleController.jsx
=> Fix 404 bug

src/components/main/ArticleController.jsx
Must've been introduced in #398 haha, I guess I only tested whether the one that wasn't giving 404 before was now <.<, my fix was apparently just making all article become 404!
=> Fix eternal 404 on every article (lol horrendous bug)

src/components/admin/article/ArticleController.jsx, src/components/admin/article/__tests__/articleLogic.test.js, src/components/admin/article/articleLogic.js
I wanted to stick to writing regression tests for all bugs we fix, so I did a refactor to make some pure functions that are more easily testable, I'll comment where the actual change is. 
I actually really like this structure of my refactor, think we should do more of it, trying to isolate all the side effects in a few functions and then extract all the pure logic behaviour out into separate functions that are easily unit testable
=> Fix saving without authors

CODEOWNERS
@zanemountcastle I'm assuming that you want to stop all the annoying notifications now that you've graduated?
=> Remove Zane as a code owner

.circleci/config.yml
Just submitting a PR for good form and to double check I didn't make any other stupid additions. Will instant merge
=> Fix deployment commands

deployment-resources/scripts/finalize-deployment.sh
Another one just to double check, will instant merge as well after checking diff
=> Fix deployment error handling and paths

src/components/admin/form-components/withSelector.jsx
=> Fix Deleting Authors

database-management/migrations/20180911155617_make_issue_order_issue_number.js, database-management/seeds/lib/add-dummy-issues.js, src/components/admin/IssueListController.jsx, src/lib/db.js, src/lib/falcor/routes/issues/__tests__/by-number.test.js, src/lib/falcor/routes/issues/by-number.js, src/lib/falcor/routes/issues/meta.js
#443 
I changed our front end (though it's actually a very small surface) to use issue_number instead of issueNumber when interfacing with Falcor. And also wrote a database migration that renames issue_order to issue_number in the database, and made an accompanying find and replace to rename relevant places.
I also added a serverside verification of the issue being created
Manual testing and a unit testing of the verification
=> #443 fix creating issue

src/components/admin/IssueArticleController.jsx, src/components/admin/form-components/SearchBar.jsx, src/components/admin/form-components/withFalcorSearch.jsx
An article added to an issue gave you a validation error
Manually (What is our setup to mock a component and Unit Test it's functions?)
=> Fix add article

src/lib/utilities.js
=> Add navya to whitelist

src/lib/db.js, src/lib/falcor/routes/issues/by-number.js
There was a typo which made the cache not update correctly (wouldn't have happened with Typescript!), and also added some catch statements. Our promise code is really bad at the moment :'(
=> Fix cache updating of creating new issue

src/components/admin/IssueArticleController.jsx
There was a typo in the parentheses
=> Fix search by list

src/components/admin/IssueArticleController.jsx
We at some point changed byPage to be 0-indexed instead of 1-indexed and it seems like we didn't change that here
=> Fix search by list offset

src/components/admin/MainIssueController.jsx
Haven't been able to reproduce locally but this may handle #455 and fix the publishing error
=> Attempt at date picker fix

src/components/admin/lib/constants.js, src/lib/utilities.js
=> Administrative updates

src/components/admin/lib/constants.js, src/lib/utilities.js
=> Deploy administrative updates

src/components/admin/article/ArticleController.jsx, src/components/admin/article/article-logic.ts, src/components/admin/article/components/ArticlePreview.jsx, src/components/main/Article.jsx, src/components/main/ArticleBody.jsx, src/server-code/admin-server.js, static/admin.css
=> Add article preview

src/lib/utilities.js
=> Add Jocelyn and Paula to whitelist

src/lib/utilities.js
=> Deploy admin whitelist updates

src/components/admin/__tests__/form-components/validated-fields.test.js, src/components/admin/article/ArticleController.jsx, src/components/admin/article/CreateArticleController.jsx, src/components/admin/form-components/validated-fields.jsx
Added a validator to make sure the slug is in a good format that shouldn't be error prone and makes nice links to copy and paste.
I added a test for the validator (and the other validators) as well as made sure it worked in the editor.
=> Fix editor bad slugs

src/components/admin/__tests__/form-components/validated-fields.test.js, src/components/admin/form-components/validated-fields.jsx
=> Add 0 to slug validation

.gitignore, src/lib/db.js
#467 Related Articles display itself
Added if statement to skip adding number of common tags if article is itself
Ran locally with an article that showed itself in related articles; after change the article itself no longer showed up
=> Exclude current article from related articles

.github/CODEOWNERS
Make Nav a codeowner to make it possible to do code reviews and merge branches without Emil's review every single time
=> Add Nav to be a codeowner

docs/dev-environment/setting-up-dev-environment.md
Slight modification to the documentation - added SSH guide
=> Added SSH guide to Documentation

docs/dev-environment/README.md
Small fix in a typo for documentation, fixed.
=> Small fix in a typo that broke the link

src/components/admin/article/ArticleController.jsx
#466 
Editors are able to preview author names
=> implemented author preview

src/lib/utilities.js
Quick Patch to give admin access to new user
=> Add Sameera Singh to Google Whitelist

static/admin.css
closes #466 
I have change the css for admin page. I have added relative size, instead of absolute.
The changes were tested by running the server before and after changes and putting the page in various sizes and after changes, it still acted desirably. This can be seen one screenshots below.
Before: 
After:
=> Fully fixed the iframe tag issue in preview section

src/components/main/ArchivesController.jsx
We never made an issue for it, but it was a problem: all the issues after issue 149 stopped showing up in archives
Increased issue limit as a temporary fix, but we'll need to make a decision about how to display issues in the future as the number keeps increasing: do we want to make pages with say 50 issues each or load more only as the user scrolls more? Increasing the limit like this won't scale and likely slows down the page load.
Tested it locally, worked like a charm
Before: 
After:
=> Increase issue limit

src/lib/utilities.js
Merging new patch, adding editors to whitelist
=> Adding more Editors to Google whitelist

src/lib/utilities.js
Merge PR for updating Google Whitelist to add new editorss
=> Merge PR for updating WhiteList

src/lib/utilities.js
=> Merge to stable for teams moving to top, fixes #504

src/lib/utilities.js
PR to add email to the admin page
=> Adding author to whitelist

src/lib/utilities.js
=> Updated google whitelist for Fall 2020 team

package-lock.json, package.json, src/lib/utilities.js
=> Master -> Stable after updating whitelist

src/lib/utilities.js
=> More members added to whitelist

src/lib/utilities.js
=> Adding users to whitelist

docs/dev-environment/setting-up-dev-environment.md
N/A
updated setup dev README at mariaDB setup part, specify that you want to install the 10.2 version of mariaDB-server. 
N/A
N/A
=> updated setup readme for database part

src/lib/utilities.js
=> Added more members to the google whitelist

.circleci/config.yml, src/lib/utilities.js
=> Merging to stable after adding new members to google whitelist

src/components/admin/IssueListController.jsx
https://github.com/thegazelle-ad/gazelle-server/issues/530
Fixes #530 
- [x ] My code follows the code style of this project. (see the [style guide](https://github.com/thegazelle-ad/gazelle-server/tree/master/docs/the-gazelle-style-guide.md))
- [] Coveralls reported increased code coverage, and full coverage for all the code I added / changed (or I have a good reason that I explained above for why this is not the case)
=> Fix Issue#530 - Issues Dropdown only showing up to 200 issues

src/components/admin/IssueListController.jsx, src/lib/utilities.js
=> merge master into stable

src/lib/utilities.js, src/server-code/main-server.js
https://github.com/thegazelle-ad/gazelle-server/issues/533
=> add robots.txt in production
